name: trigger-book-build
on:
  pull_request:

jobs:
  build:
    uses: ktyle/cookbook-actions/.github/workflows/build-book.yaml@add-aq-api-keys
    with:
      environment_name: cookbook-dev
      artifact_name: book-zip-${{ github.event.number }}
      # Other input options are possible, see ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml
